name: Continuous Integration and Delivery 

on: [push]

env:
  USERS: docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/test-driven-users:prod
  CLIENT: docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/test-driven-client:prod
  REACT_APP_API_SERVICE_URL: "http://localhost:5004"

jobs:
  
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Images
        run: |
          docker pull ${{ env.USERS }} || true
          docker pull ${{ env.CLIENT }} || true
      - name: Build Images
        run: |
          docker build \
            --file services/users/Dockerfile.prod \
            --tag ${{ env.USERS }} \
            "./services/users"
          docker build \
            --file services/client/Dockerfile.prod \
            --tag ${{ env.CLIENT }} \
            --build-arg NODE_ENV=production \
            --build-arg REACT_APP_API_SERVICE_URL=${{ env.REACT_APP_API_SERVICE_URL }} \
            "./services/client"
      - name: Push Images
        run: |
          docker push ${{ env.USERS }}
          docker push ${{ env.CLIENT }}


